Repository magento/ece-tools, pull requests merged in 2019-11, with the labels that each got.

#636 MAGECLOUD-4568: Travis is failing with PRs from forks into ECE-Tools
  .travis.yml
  tests/travis/prepare_functional_parallel.sh
Labels: Release: 2002.1.0, approved

#640 MAGECLOUD-4454: Add one more index to Travis CI FT
  .travis.yml
  src/Test/Functional/Acceptance/ElasticSearch23Php72Cest.php
  tests/travis/prepare_functional_parallel.sh
Labels: Release: 2002.1.0, approved

#637 MAGECLOUD-4514: Automate test for session configuration
  src/Test/Functional/Acceptance/SessionConfigurationCest.php
Labels: Release: 2002.0.1, approved

#625 MAGECLOUD-4076: Service EOL validation
  composer.json
  config/eol.yaml
  config/services.xml
  scenario/deploy.xml
  src/Config/Validator/Deploy/ServiceEol.php
  src/Config/ValidatorInterface.php
  src/Filesystem/FileList.php
  src/Service/EolValidator.php
  src/Service/Php.php
  src/Service/ServiceFactory.php
  src/Test/Unit/Config/Validator/Deploy/ServiceEolTest.php
  src/Test/Unit/Service/EolValidatorTest.php
  src/Test/Unit/Service/PhpTest.php
  src/Test/Unit/Service/_file/eol.yaml
  src/Test/Unit/Service/_file/eol_2.yaml
  src/Test/Unit/Step/SkipStepTest.php
Labels: Release: 2002.1.0, approved

#645 MAGECLOUD-4670: Release ECE-Tools 2002.0.22
  composer.json
Labels: 2002.0, Release: 2002.0.22, approved

#638 MAGECLOUD-4569: Upgrading PHPUnit and refactoring expected exceptions.
  composer.json
  src/Test/Unit/App/ErrorHandlerTest.php
  src/Test/Unit/App/Logger/Gelf/TransportFactoryTest.php
  src/Test/Unit/App/Logger/HandlerFactoryTest.php
  src/Test/Unit/Command/BackupListTest.php
  src/Test/Unit/Command/BackupRestoreTest.php
  src/Test/Unit/Command/ConfigDumpTest.php
  src/Test/Unit/Command/CronUnlockTest.php
  src/Test/Unit/Command/DbDumpTest.php
  src/Test/Unit/Config/GlobalSectionTest.php
  src/Test/Unit/Config/LogTest.php
  src/Test/Unit/Config/Stage/BuildTest.php
  src/Test/Unit/Config/Stage/Deploy/MergedConfigTest.php
  src/Test/Unit/Config/Stage/DeployTest.php
  src/Test/Unit/Config/Stage/PostDeployTest.php
  src/Test/Unit/Config/StateTest.php
  src/Test/Unit/Config/System/VariablesTest.php
  src/Test/Unit/DB/ConnectionTest.php
  src/Test/Unit/DB/Data/ConnectionFactoryTest.php
  src/Test/Unit/DB/Data/RelationshipConnectionFactoryTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/CopyStrategyTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/CopySubFolderStrategyTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/StrategyFactoryTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/SubSymlinkStrategyTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/SymlinkStrategyTest.php
  src/Test/Unit/Filesystem/DirectoryListTest.php
  src/Test/Unit/Filesystem/Driver/FileTest.php
  src/Test/Unit/Filesystem/Flag/ManagerTest.php
  src/Test/Unit/Package/ManagerTest.php
  src/Test/Unit/Scenario/Collector/ScenarioTest.php
  src/Test/Unit/Scenario/Collector/StepTest.php
  src/Test/Unit/Scenario/MergerTest.php
  src/Test/Unit/Scenario/PathResolverTest.php
  src/Test/Unit/Scenario/ProcessorTest.php
  src/Test/Unit/Scenario/ResolverTest.php
  src/Test/Unit/Service/ServiceFactoryTest.php
  src/Test/Unit/Shell/ShellTest.php
  src/Test/Unit/Shell/UtilityManagerTest.php
  src/Test/Unit/Step/Build/ComposerDumpAutoloadTest.php
  src/Test/Unit/Step/Build/DeployStaticContent/GenerateTest.php
  src/Test/Unit/Step/Build/RefreshModulesTest.php
  src/Test/Unit/Step/Deploy/DeployStaticContent/GenerateTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/PrepareConfigTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/SearchEngineTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/Install/SetupTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/Update/SetupTest.php
  src/Test/Unit/Step/Deploy/InstallUpdateTest.php
  src/Test/Unit/Step/DisableMaintenanceModeTest.php
  src/Test/Unit/Step/EnableMaintenanceModeTest.php
  src/Test/Unit/Step/PostDeploy/CleanCacheTest.php
  src/Test/Unit/Step/PostDeploy/DeployFailedTest.php
  src/Test/Unit/Step/SetProductionModeTest.php
  src/Test/Unit/Step/ValidateConfigurationTest.php
  src/Test/Unit/Util/MaintenanceModeSwitcherTest.php
  src/Test/Unit/Util/StaticContentCompressorTest.php
  src/Test/Unit/Util/UrlManagerTest.php
Labels: Release: 2002.1.0, approved

#643 MAGECLOUD-4669: Add EOL for Redis 3.2
  config/eol.yaml
Labels: approved

#648 MAGECLOUD-4518: Create autotest to install community edition
  .travis.yml
  src/Config/ValidatorInterface.php
  src/Scenario/Processor.php
  src/Test/Functional/Acceptance/AbstractCest.php
  src/Test/Functional/Acceptance/AbstractInstallCest.php
  src/Test/Functional/Acceptance/AcceptanceCeCest.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  tests/functional/Codeception/Docker.php
  tests/functional/_support/.gitignore
  tests/functional/_support/_generated/.gitignore
  tests/travis/functional_ce.sh
  tests/travis/functional_ee.sh
Labels: Release: 2002.1.0, approved
