Repository magento/ece-tools, pull requests merged in 2019-03, with the labels that each got.

#427 MAGECLOUD-3228: Installation from git is broken with 2.3.1-develop due to ElasticSerch 6.5
  src/Command/Dev/UpdateComposer/ClearModuleRequirements.php
Labels: approved

#428 MAGECLOUD-3223: Add Redis 5 Image to Cloud Docker
  src/Docker/Service/ServiceFactory.php
Labels: approved

#426 MAGECLOUD-3196: Add ElasticSearch 6.x Support to Cloud
  src/Docker/Service/ServiceFactory.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/SearchEngine/Config.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/SearchEngine/ConfigTest.php
Labels: approved

#429 MAGECLOUD-3231: Rewrite AcceptanceTest to use Cloud Docker
  .travis.yml
  src/Command/Docker/BuildIntegration.php
  src/Docker/BuilderFactory.php
  src/Docker/IntegrationV1Builder.php
  src/Docker/IntegrationV2Builder.php
  src/Test/DockerIntegration/AcceptanceTest.php
  src/Test/DockerIntegration/Upgrade21Test.php
  src/Test/DockerIntegration/Upgrade22Test.php
  src/Test/DockerIntegration/UpgradeTest.php
  src/Test/Integration/Upgrade22Test.php
  src/Test/Integration/UpgradeTest.php
  src/Test/Unit/Command/Docker/BuildIntegrationTest.php
  src/Test/Unit/Docker/IntegrationBuilderTest.php
  tests/docker-integration/AbstractTest.php
  tests/docker-integration/Config.php
  tests/docker-integration/Process/Bash.php
  tests/docker-integration/Process/ComposerInstall.php
  tests/docker-integration/Process/ComposerRequire.php
  tests/docker-integration/Process/Curl.php
  tests/docker-integration/Process/Ece.php
  tests/docker-integration/Process/EnvDown.php
  tests/docker-integration/Process/EnvUp.php
  tests/docker-integration/Process/GitClone.php
  tests/docker-integration/Process/Process.php
  tests/travis/script.sh
Labels: review

#430 MAGECLOUD-3246: Add --use-rewrites option to install command, MAGECLOUD-2895: The var/log/install_upgrade.log is useless without dividers and timestamps
  src/Process/Deploy/InstallUpdate/Install/Setup.php
  src/Process/Deploy/InstallUpdate/Update/Setup.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Install/SetupTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Update/SetupTest.php
Labels: qa

#431 MAGECLOUD-3275: Rewrite ConfigDumpTest to use Cloud Docker
  src/Docker/IntegrationV2Builder.php
  src/Test/DockerIntegration/AcceptanceTest.php
  src/Test/DockerIntegration/Upgrade21Test.php
  src/Test/DockerIntegration/Upgrade22Test.php
  src/Test/DockerIntegration/UpgradeTest.php
  src/Test/Integration/CommandDumpTest.php
  tests/docker-integration/Process/Copy.php
Labels: review

#425 MAGECLOUD-2870: Static assets compression shouldn't break a deploy
  dist/.magento.env.yaml
  src/App/Container.php
  src/Config/Database/MergedConfig.php
  src/Config/Schema.php
  src/Config/StageConfigInterface.php
  src/DB/Connection.php
  src/DB/Dump.php
  src/Process/Build/CompressStaticContent.php
  src/Process/Deploy/CompressStaticContent.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/DbConnection.php
  src/Process/Deploy/InstallUpdate/Install/Setup.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/DB/ConnectionTest.php
  src/Test/Unit/Process/Build/CompressStaticContentTest.php
  src/Test/Unit/Process/Deploy/CompressStaticContentTest.php
  src/Test/Unit/Util/StaticContentCompressorTest.php
  src/Util/StaticContentCompressor.php
Labels: approved

#433 MAGECLOUD-3343: Add latest patches to ECE-Tools
  patches.json
  patches/MC-5964__preauth_sql__2.1.4.patch
  patches/MC-5964__preauth_sql__2.2.0.patch
  patches/MC-5964__preauth_sql__2.3.0.patch
Labels: approved

#436 Merge 2002.0 into develop
  composer.json
Labels: approved
