Repository magento/ece-tools, pull requests merged in 2019-01, with the labels that each got.

#405 MAGECLOUD-3046: [Cloud Docker] Remove deprecated CLI container
  dist/Makefile
  src/Docker/DevBuilder.php
  src/Test/Unit/Docker/DevBuilderTest.php
Labels: qa

#399 MAGECLOUD-2904: SCD_EXCLUDE_THEMES / SCD_MATRIX - Resolve Issues with Case-sensitive theme name
  src/StaticContent/CommandFactory.php
  src/StaticContent/ThemeResolver.php
  src/Test/Unit/StaticContent/CommandFactoryTest.php
  src/Test/Unit/StaticContent/ThemeResolverTest.php
Labels: approved

#407 MAGECLOUD-3048: Allow setting of x-frame options within configuration…
  dist/.magento.env.yaml
  src/Config/Schema.php
  src/Config/StageConfigInterface.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/PrepareConfig.php
  src/Process/Deploy/PreDeploy/RestoreWritableDirectories.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/PrepareConfigTest.php
  src/Test/Unit/Process/Deploy/PreDeploy/RestoreWritableDirectoriesTest.php
Labels: approved

#400 MAGECLOUD-2963: Add Variable to Configure 'resource' section of env.php (database connection settings)
  dist/.magento.env.yaml
  src/App/Container.php
  src/Config/Database/ResourceConfig.php
  src/Config/Schema.php
  src/Config/Stage/DeployInterface.php
  src/Config/Validator/Deploy/ResourceConfiguration.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/DbConnection.php
  src/Test/Unit/Config/Database/ResourceConfigTest.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Config/Validator/Deploy/ResourceConfigurationTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/DbConnectionTest.php
Labels: review

#404 Bad constraint "symfony/yaml": "^2.3||^3.3"
  composer.json
Labels: approved, community

#396 MAGECLOUD-2903: Add PHP Version Validation
  src/App/Container.php
  src/Config/Validator/Deploy/PhpVersion.php
  src/Test/Unit/Config/Validator/Deploy/PhpVersionTest.php
Labels: approved

#412 MAGECLOUD-2882: Duplication beetwen SCD_EXCLUDE_THEME and SCD_MATRIX
  dist/.magento.env.yaml
  src/App/Container.php
  src/Config/Schema.php
  src/Config/StageConfigInterface.php
  src/Config/Validator/Build/StageConfigDeprecatedVariables.php
  src/Config/Validator/Deploy/DeprecatedVariables.php
  src/Test/Unit/Config/Validator/Build/StageConfigDeprecatedVariablesTest.php
  src/Test/Unit/Config/Validator/Deploy/DeprecatedVariablesTest.php
Labels: qa

#413 Move compression from generate to transfer (#191853)
  src/App/Container.php
Labels: Partner: Tryzens, partners-contribution, qa
