Repository magento/ece-tools, pull requests merged in 2019-06, with the labels that each got.

#530 MAGECLOUD-3611: Multi-threaded SCD Doesn’t Work as Expected
  patches.json
  patches/MAGECLOUD-3611__multi_thread_scd__2.2.0.patch
  patches/MAGECLOUD-3611__multi_thread_scd__2.2.4.patch
  patches/MAGECLOUD-3611__multi_thread_scd__2.3.0.patch
  patches/MAGECLOUD-3611__multi_thread_scd__2.3.2.patch
Labels: approved

#528 MAGECLOUD-3678: Add validation for node
  dist/docker/bin/docker
  src/Command/Docker/Build.php
  src/Command/Docker/Build/Writer.php
  src/Command/Docker/BuildIntegration.php
  src/Docker/Compose/DeveloperCompose.php
  src/Docker/Compose/FunctionalCompose.php
  src/Docker/Compose/IntegrationCompose.php
  src/Docker/Compose/ProductionCompose.php
  src/Docker/ComposeFactory.php
  src/Docker/ComposeInterface.php
  src/Docker/Config/Relationship.php
  src/Docker/Service/Config.php
  src/Docker/Service/ServiceFactory.php
  src/Service/Service.php
  src/Service/Validator.php
  src/Test/Unit/Command/Docker/Build/WriterTest.php
  src/Test/Unit/Command/Docker/BuildTest.php
  src/Test/Unit/Docker/Service/ConfigTest.php
  src/Test/Unit/Service/ValidatorTest.php
Labels: Release: 2002.0.20, approved

#516 MAGECLOUD-3486: [Cloud Docker] Add validations to improve error handling
  src/Command/Docker/Build.php
  src/Test/Unit/Command/Docker/BuildTest.php
Labels: Release: 2002.0.20

#486 Added cloud:config command to display encoded variables
  src/Application.php
  src/Command/ConfigShow.php
  src/Command/ConfigShow/Renderer.php
  src/Test/Unit/ApplicationTest.php
  src/Test/Unit/Command/ConfigShow/RendererTest.php
  src/Test/Unit/Command/ConfigShowTest.php
Labels: Release: 2002.0.20, approved, community

#532 MAGECLOUD-3159: Improve git installation flow
  src/Command/Dev/UpdateComposer.php
  src/Command/Dev/UpdateComposer/ClearModuleRequirements.php
  src/Command/Dev/UpdateComposer/ComposerGenerator.php
  src/Test/Unit/Command/Dev/UpdateComposer/ClearModuleRequirementsTest.php
  src/Test/Unit/Command/Dev/UpdateComposer/ComposerGeneratorTest.php
  src/Test/Unit/Command/Dev/UpdateComposer/_files/clear_module_requirements.php
  tests/static/phpcs-ruleset.xml
  tests/static/phpmd-ruleset.xml
Labels: Release: 2002.0.20, approved

#533 MAGECLOUD-3559: [Spike] Check how mutagen.io can improve performance of cloud docker environment
  composer.json
  dist/mutagen.sh
  src/Command/Docker/Build.php
  src/Docker/Compose/DeveloperCompose.php
  src/Test/Unit/Command/Docker/BuildTest.php
Labels: Release: 2002.0.20, approved

#540 Update README.md to Mention Related Modules & Update URLs
  README.md
Labels: Release: 2002.0.20, approved

#542 MAGECLOUD-3761: Eliminate Docker Integration Testing framework
  composer.json
  src/Application.php
  src/Command/Docker/BuildIntegration.php
  src/Docker/Compose/IntegrationCompose.php
  src/Docker/ComposeFactory.php
  src/Test/Integration/MagentoEnvYamlTest.php
  src/Test/Integration/ShellLoggingTest.php
  src/Test/Unit/ApplicationTest.php
  tests/README.md
  tests/integration/.gitignore
  tests/integration/AbstractTest.php
  tests/integration/Application.php
  tests/integration/Bootstrap.php
  tests/integration/Shell/Shell.php
  tests/integration/etc/.gitignore
  tests/integration/etc/.magento.env.yaml.dist
  tests/integration/etc/build_options.ini.dist
  tests/integration/etc/environment.php.dist
  tests/integration/phpunit.xml.dist
  tests/travis/integration.sh
Labels: approved

#505 MAGECLOUD-3258: Cache Warm-up, Using RegEx to Warm-up Multiple Pages
  .travis.yml
  composer.json
  src/App/Container.php
  src/Filesystem/Driver/File.php
  src/Process/PostDeploy/WarmUp.php
  src/Process/PostDeploy/WarmUp/Urls.php
  src/Process/PostDeploy/WarmUp/UrlsPattern.php
  src/Test/Functional/Acceptance/PostDeployCest.php
  src/Test/Functional/Acceptance/UpgradeCest.php
  src/Test/Unit/Process/PostDeploy/WarmUp/UrlsPatternTest.php
  src/Test/Unit/Process/PostDeploy/WarmUp/UrlsTest.php
  src/Test/Unit/Process/PostDeploy/WarmUpTest.php
  src/Test/Unit/Util/UrlManagerTest.php
  src/Util/UrlManager.php
Labels: Release: 2002.0.20, qa

#541 MAGECLOUD-3357: [Cloud Docker] Changes in .magento.app.yaml should affect php modules
  src/Docker/Compose/FunctionalCompose.php
  src/Docker/Compose/PhpExtension.php
  src/Docker/Compose/ProductionCompose.php
  src/Docker/Config/Reader.php
  src/Docker/Service/Config.php
  src/Test/Unit/Docker/Compose/PhpExtensionTest.php
  src/Test/Unit/Docker/Config/ReaderTest.php
Labels: Release: 2002.0.20, approved

#537 MAGECLOUD-3642: Time to First Byte Test
  dist/.magento.env.yaml
  src/App/Container.php
  src/Config/Schema.php
  src/Config/Stage/PostDeployInterface.php
  src/Docker/Compose/FunctionalCompose.php
  src/Filesystem/FileList.php
  src/Http/PoolFactory.php
  src/Http/TransferStatsHandler.php
  src/Process/PostDeploy/TimeToFirstByte.php
  src/Process/PostDeploy/WarmUp.php
  src/Process/PostDeploy/WarmUp/Urls.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Filesystem/FileListTest.php
  src/Test/Unit/Http/PoolFactoryTest.php
  src/Test/Unit/Http/TransferStatsHandlerTest.php
  src/Test/Unit/Process/PostDeploy/TimeToFirstByteTest.php
  src/Test/Unit/Process/PostDeploy/WarmUp/UrlsTest.php
  src/Test/Unit/Process/PostDeploy/WarmUpTest.php
  src/Test/Unit/Util/UrlManagerTest.php
  src/Util/UrlManager.php
Labels: Release: 2002.0.20, approved

#546 Reduce log level of shell output
  src/Shell/Shell.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Functional/Acceptance/AdminCredentialCest.php
  src/Test/Functional/Acceptance/PatchApplierCest.php
  src/Test/Unit/Shell/ShellTest.php
  tests/functional/_data/files/debug_logging/.magento.env.yaml
Labels: Release: 2002.0.20, approved

#551 MAGECLOUD-3850: [CLOUD Docker] Disabled extensions are still displayed in php container
  src/Docker/Compose/ProductionCompose.php
Labels: Release: 2002.0.20, qa
