Repository magento/ece-tools, pull requests merged in 2019-09, with the labels that each got.

#597 MAGECLOUD-4217: Forward-port changes
  composer.json
  dist/.magento.env.yaml
  patches.json
  patches/MAGECLOUD-4071__terminate_consumers_if_the_queue_is_empty__2.2.0.patch
  patches/MAGECLOUD-4071__terminate_consumers_if_the_queue_is_empty__2.3.2.patch
  src/App/Container.php
  src/Config/Schema.php
  src/Config/Stage/DeployInterface.php
  src/Process/Deploy/BackgroundProcessKill.php
  src/Process/Deploy/DisableCron.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/Amqp/Config.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Process/Deploy/BackgroundProcessKillTest.php
  src/Test/Unit/Process/Deploy/DisableCronTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/Amqp/ConfigTest.php
Labels: approved

#588 MAGECLOUD-3873 - Static Content Copy Deprecation Warning
  src/Config/Stage/Deploy/MergedConfig.php
  src/Config/Stage/DeployInterface.php
  src/Config/Validator/Deploy/DeprecatedVariables.php
  src/Test/Unit/Config/Stage/Deploy/MergedConfigTest.php
  src/Test/Unit/Config/Validator/Deploy/DeprecatedVariablesTest.php
Labels: Release: 2002.1.0, approved

#590 MAGECLOUD-3874: Remove support if build_options.ini and fail build if it's present
  src/App/Container.php
  src/Config/Build/Reader.php
  src/Config/Stage/Build.php
  src/Config/Validator/Build/BuildOptionsIni.php
  src/Config/Validator/Build/ScdOptionsIgnorance.php
  src/Config/Validator/Build/UnsupportedBuildOptionsIni.php
  src/Filesystem/ConfigFileList.php
  src/Test/Unit/Config/Build/ReaderTest.php
  src/Test/Unit/Config/Stage/BuildTest.php
  src/Test/Unit/Config/Validator/Build/BuildOptionsIniTest.php
  src/Test/Unit/Config/Validator/Build/ScdOptionsIgnoranceTest.php
  src/Test/Unit/Config/Validator/Build/UnsupportedBuildOptionsIniTest.php
Labels: Release: 2002.1.0, approved

#599 MAGECLOUD-4242: Refactor ece-tools functional tests
  .docker/global.env
  .travis.yml
  codeception.dist.yml
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Functional/Acceptance/PatchApplierCest.php
  tests/functional/Robo/Tasks/DockerCompose/Run.php
  tests/functional/configuration.dist.yml
Labels: Release: 2002.1.0

#604 MAGECLOUD-4284: Command "docker cp" sets wrong file owner and permissions
  src/Test/Functional/Acceptance/AcceptanceCest.php
  tests/functional/Robo/Tasks/CopyToDocker.php
Labels: Release: 2002.1.0, approved

#605 MAGECLOUD-4283: Fix .gitignore file
  .gitignore
Labels: Release: 2002.1.0, approved

#600 MAGECLOUD-4248: Automate CronUnlockingCest test in ece-tools.
  .gitignore
  src/Test/Functional/Acceptance/CronUnlockCest.php
Labels: Release: 2002.1.0, approved

#585 MAGECLOUD-4022 - PHP 7.3 Test Coverage
  .travis.yml
  src/Test/Functional/Acceptance/UpgradeCest.php
  tests/functional/Codeception/Docker.php
  tests/travis/functional.sh
  tests/travis/prepare_functional_parallel.sh
Labels: Release: 2002.1.0, approved

#608 MAGECLOUD-4272: Remove twig/twig from ECE-Tools Dependencies
  composer.json
  src/App/Container.php
  src/Filesystem/DirectoryList.php
  src/Process/Deploy/InstallUpdate/Install/ResetPassword.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Install/ResetPasswordTest.php
  src/Test/Unit/View/TwigRendererTest.php
  src/Test/Unit/View/_files/sample.html.twig
  src/View/RendererInterface.php
  src/View/TwigRenderer.php
  views/reset_password.html
Labels: Release: 2002.1.0, approved

#614 MAGECLOUD-4235 Automate SCD_STRATEGY functional test
  src/Test/Functional/Acceptance/ScdStrategyCest.php
  tests/functional/_data/files/scd/scd-strategy-compact.yaml
  tests/functional/_data/files/scd/scd-strategy-quick.yaml
  tests/functional/_data/files/scd/scd-strategy-standard.yaml
Labels: Release: 2002.1.0, approved, review
