Repository magento/ece-tools, pull requests merged in 2019-10, with the labels that each got.

#617 MAGECLOUD-4322: Automate test for environment variables validation
  src/Test/Functional/Acceptance/DataTypesOptionValidationCest.php
Labels: Release: 2002.1.0, approved

#613 MAGECLOUD-4292: FT Take Longer than Before Because of composer/cache …
  .docker/global.env
  .travis.yml
Labels: Release: 2002.1.0, approved

#618 MAGECLOUD-4100: Introduce DI component
  composer.json
  config/services.xml
  scenario/build/generate.xml
  scenario/build/transfer.xml
  scenario/deploy.xml
  scenario/post-deploy.xml
  src/App/Container.php
  src/App/ContainerInterface.php
  src/Config/RepositoryFactory.php
  src/Config/Validator/ResultFactory.php
  src/Filesystem/DirectoryCopier/SubSymlinkStrategy.php
  src/Scenario/Merger.php
  src/Scenario/Resolver.php
  src/Shell/ProcessFactory.php
  src/Shell/Shell.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/Urls.php
  src/Step/StepComposite.php
  src/Test/Unit/Config/RepositoryFactoryTest.php
  src/Test/Unit/Config/Validator/ResultFactoryTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/SubSymlinkStrategyTest.php
  src/Test/Unit/Shell/ProcessFactoryTest.php
  src/Test/Unit/Shell/ShellTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/UrlsTest.php
  src/Test/Unit/Step/StepCompositeTest.php
Labels: Release: 2002.1.0, approved

#609 MAGECLOUD-4264: Deliver patches for MSI
  patches.json
  patches/MSI-2210__price_indexer_fails_with_large_catalogs__1.0.3.patch
  patches/MSI-GH-2350__avoid_quering_inventory_default_stock_view_in_storefront__1.0.3.patch
  patches/MSI-GH-2515__eliminate_group_concat_from_source_item_indexer__configurable-product-indexer__1.0.3.patch
  patches/MSI-GH-2515__eliminate_group_concat_from_source_item_indexer__grouped-product-indexer__1.0.3.patch
  patches/MSI-GH-2515__eliminate_group_concat_from_source_item_indexer__indexer__1.0.3.patch
  patches/MSI-GH-2515__eliminate_group_concat_from_source_item_indexer__reservations__1.0.3.patch
  src/Step/Deploy/PreDeploy/ConfigUpdate/Cache.php
Labels: Release: 2002.1.0, approved

#621 MAGECLOUD-4392: Clean-up ECE-Tools
  autoload.php
  bootstrap.php
  composer.json
  config/README.md
  m2-ece-build
  m2-ece-deploy
  m2-ece-scd-dump
  scenario/build/generate.xml
  scenario/build/transfer.xml
  scenario/deploy.xml
  scenario/post-deploy.xml
  src/Application.php
  src/Command/Docker/Build.php
  src/Command/Docker/GenerateDist.php
  src/Filesystem/FileList.php
  src/Test/Unit/ApplicationTest.php
  tests/functional/Robo/Tasks/GenerateDockerCompose.php
  tests/static/phpstan.neon
Labels: Release: 2002.1.0, approved

#601 MAGECLOUD-3392: Reduce q-ty of Reports Created in /app/*/var/report
  dist/.magento.env.yaml
  patches.json
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.1.17.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.1.4.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.1.8.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.2.0.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.2.5.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.2.6.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.2.8.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.3.0.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.3.1.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.3.2.patch
  scenario/build/generate.xml
  scenario/deploy.xml
  src/Config/Environment.php
  src/Config/Schema.php
  src/Config/Stage/BuildInterface.php
  src/Config/Validator/Deploy/ReportDirNestingLevel.php
  src/Filesystem/ConfigFileList.php
  src/Step/Build/SetReportDirNestingLevel.php
  src/Test/Functional/Acceptance/ReportDirNestingLevelCest.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Config/Validator/Deploy/ReportDirNestingLevelTest.php
  src/Test/Unit/Filesystem/ConfigFileListTest.php
  src/Test/Unit/Step/Build/SetErrorReportDirNestingLevelTest.php
  tests/functional/_data/files/report_dir_nesting_level/.magento.env.yaml
  tests/functional/_data/files/report_dir_nesting_level/invalid_local.xml
  tests/functional/_data/files/report_dir_nesting_level/local_with_property.xml
  tests/functional/_data/files/report_dir_nesting_level/local_without_property.xml
Labels: Release: 2002.1.0, approved

#622 MAGECLOUD-4383: Automate test for DB configuration
  src/Test/Functional/Acceptance/DatabaseConfigurationCest.php
  tests/functional/Robo/Tasks/CopyToDocker.php
Labels: approved

#624 MAGECLOUD-4428: [2002.0] Deliver patches for MSI
  patches.json
  patches/MSI-2210__price_indexer_fails_with_large_catalogs__1.0.3.patch
  patches/MSI-GH-2350__avoid_quering_inventory_default_stock_view_in_storefront__1.0.3.patch
  patches/MSI-GH-2515__eliminate_group_concat_from_source_item_indexer__configurable-product-indexer__1.0.3.patch
  patches/MSI-GH-2515__eliminate_group_concat_from_source_item_indexer__grouped-product-indexer__1.0.3.patch
  patches/MSI-GH-2515__eliminate_group_concat_from_source_item_indexer__indexer__1.0.3.patch
  patches/MSI-GH-2515__eliminate_group_concat_from_source_item_indexer__reservations__1.0.3.patch
Labels: Release: 2002.0.22, approved

#620 MAGECLOUD-4109: Introduce extensibility mechanism based on Dependency Injection
  composer.json
  config/scenario.xsd
  config/services.xml
  scenario/build/generate.xml
  scenario/build/transfer.xml
  scenario/deploy.xml
  scenario/post-deploy.xml
  src/App/Container.php
  src/ExtensionRegistrar.php
  src/Scenario/Collector/Scenario.php
  src/Scenario/Collector/Step.php
  src/Scenario/Merger.php
  src/Scenario/PathResolver.php
  src/Scenario/Processor.php
  src/Scenario/Resolver.php
  src/Scenario/Sorter.php
  src/Step/SkipStep.php
  src/Step/ValidateConfiguration.php
  src/Test/Unit/Scenario/Collector/ScenarioTest.php
  src/Test/Unit/Scenario/Collector/StepTest.php
  src/Test/Unit/Scenario/MergerTest.php
  src/Test/Unit/Scenario/PathResolverTest.php
  src/Test/Unit/Scenario/ProcessorTest.php
  src/Test/Unit/Scenario/ResolverTest.php
  src/Test/Unit/Scenario/SorterTest.php
Labels: Release: 2002.1.0, approved

#628 MAGECLOUD-4105: Add coverage of new functionality to Functional Testing Framework
  src/Test/Functional/Acceptance/AbstractCest.php
  src/Test/Functional/Acceptance/ScenarioExtensibilityCest.php
  tests/functional/Codeception/Docker.php
  tests/functional/_data/files/debug_logging/.magento.env.yaml
  tests/functional/_data/packages/ece-tools-extend/.gitignore
  tests/functional/_data/packages/ece-tools-extend/README.md
  tests/functional/_data/packages/ece-tools-extend/composer.json
  tests/functional/_data/packages/ece-tools-extend/config/services.xml
  tests/functional/_data/packages/ece-tools-extend/registration.php
  tests/functional/_data/packages/ece-tools-extend/scenario/extend-build-generate-skip-di.xml
  tests/functional/_data/packages/ece-tools-extend/scenario/extend-build-generate.xml
  tests/functional/_data/packages/ece-tools-extend/scenario/extend-build-transfer.xml
  tests/functional/_data/packages/ece-tools-extend/scenario/extend-deploy.xml
  tests/functional/_data/packages/ece-tools-extend/scenario/extend-post-deploy-skip-steps.xml
  tests/functional/_data/packages/ece-tools-extend/src/Step/Build/SetProductionMode.php
  tests/functional/_data/packages/ece-tools-extend/src/Step/Build/StaticContentUpdate.php
  tests/functional/_data/packages/ece-tools-extend/src/Step/Deploy/PreDeploy.php
  tests/functional/_data/packages/ece-tools-extend/src/Step/Deploy/RemoveDeployFailedFlag.php
Labels: Release: 2002.1.0, approved

#634 Update README.md
  README.md
Labels: 2002.0, Release: 2002.0.22, approved

#631 MAGECLOUD-4474: ECE-Tools is showing wrong ES configuration on multiple config entities
  src/Service/ElasticSearch.php
  src/Test/Unit/Service/ElasticSearchTest.php
Labels: Release: 2002.1.0, approved

#633 Update README.md
  README.md
Labels: Release: 2002.1.0, approved

#635 MAGECLOUD-4355: ELASTICSUITE_CONFIGURATION is Missing _merge Parameter Syntax in .magento.env.yaml.dist
  dist/.magento.env.yaml
Labels: Release: 2002.1.0, approved
