Repository magento/ece-tools, pull requests merged in 2019-08, with the labels that each got.

#575 MAGECLOUD-3957: Error with static content deploy because of empty locale for admin user in config.php in case of dump after installation
  src/Test/Unit/Util/ArrayManagerTest.php
  src/Util/ArrayManager.php
Labels: Release: 2002.0.21, approved

#569 MAGECLOUD-3940: Use more OS agnostic form to find number of processors
  .travis.yml
  composer.json
  src/Test/Unit/Util/CpuTest.php
  src/Util/Cpu.php
Labels: Release: 2002.0.21, approved

#584 MAGECLOUD-3913: Deadlocks when consumers run from cron
  patches.json
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.5.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.6.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.7.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.8.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.3.0.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.3.1.patch
Labels: Release: 2002.0.21, qa

#583 MAGECLOUD-4009: Error in UrlManager::getBaseUrl() when secured url isn't configured
  src/Test/Unit/Util/UrlManagerTest.php
  src/Util/UrlManager.php
Labels: Release: 2002.0.21, approved

#580 MAGECLOUD-4018: Adjust Service Version Validation for 2.2.10/2.3.3 Support
  src/Service/Validator.php
Labels: Release: 2002.0.21, approved

#586 MAGECLOUD-4052: Add variable to change lock providers.
  dist/.magento.env.yaml
  src/Config/Schema.php
  src/Config/Stage/DeployInterface.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/Lock/Config.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/lock/ConfigTest.php
Labels: Release: 2002.0.21, approved

#577 MAGECLOUD-3651: Update description of variables that support _merge
  dist/.magento.env.yaml
Labels: Release: 2002.0.21, review

#589 MAGECLOUD-3871: Write cloud.log in debug level to file
  dist/.magento.env.yaml
  src/App/Logger/HandlerFactory.php
  src/Config/Log.php
  src/Test/Unit/App/Logger/HandlerFactoryTest.php
  src/Test/Unit/Config/LogTest.php
Labels: Release: 2002.0.21, approved

#592 MAGECLOUD-4128: Release ECE-Tools 2002.0.21
  composer.json
Labels: approved
