Repository magento/ece-tools, pull requests merged in 2019-12, with the labels that each got.

#647 MAGECLOUD-4423: Added error message during the deployment process in …
  src/Step/Deploy/SetCryptKey.php
  src/Test/Unit/Service/EolValidatorTest.php
  src/Test/Unit/Step/Deploy/SetCryptKeyTest.php
Labels: Partner: Zilker Technology, Release: 2002.1.0, approved, community, improvement, partners-contribution

#646 MAGECLOUD-4444: Add "products" to WARM_UP_PAGES && MAGECLOUD-4445: Add "store" to WARM_UP_PAGES logic
  src/Step/PostDeploy/WarmUp.php
  src/Step/PostDeploy/WarmUp/UrlsPattern.php
  src/Test/Unit/Step/PostDeploy/WarmUp/UrlsPatternTest.php
  src/Test/Unit/Step/PostDeploy/WarmUpTest.php
  src/Test/Unit/WarmUp/UrlsPattern/CategoryCmsPageTest.php
  src/Test/Unit/WarmUp/UrlsPattern/CommandArgumentBuilderTest.php
  src/Test/Unit/WarmUp/UrlsPattern/ConfigShowUrlCommandTest.php
  src/Test/Unit/WarmUp/UrlsPattern/PatternFactoryTest.php
  src/Test/Unit/WarmUp/UrlsPattern/ProductTest.php
  src/Test/Unit/WarmUp/UrlsPattern/StorePageTest.php
  src/Test/Unit/WarmUp/UrlsPatternTest.php
  src/Test/Unit/WarmUp/UrlsTest.php
  src/Util/UrlManager.php
  src/WarmUp/Urls.php
  src/WarmUp/UrlsPattern.php
  src/WarmUp/UrlsPattern/CategoryCmsPage.php
  src/WarmUp/UrlsPattern/CommandArgumentBuilder.php
  src/WarmUp/UrlsPattern/ConfigShowUrlCommand.php
  src/WarmUp/UrlsPattern/PatternFactory.php
  src/WarmUp/UrlsPattern/PatternInterface.php
  src/WarmUp/UrlsPattern/Product.php
  src/WarmUp/UrlsPattern/StorePage.php
Labels: Release: 2002.1.0, approved

#653 MAGECLOUD-4813: Stabilizing EOL Validation unit tests.
  src/Test/Unit/Service/EolValidatorTest.php
Labels: approved, review

#642 MAGECLOUD-3756: Implement CLI commands to enable/disable cron manually
  src/Application.php
  src/Command/CronDisable.php
  src/Command/CronEnable.php
  src/Cron/Switcher.php
  src/Step/Deploy/DisableCron.php
  src/Step/PostDeploy/EnableCron.php
  src/Test/Unit/ApplicationTest.php
  src/Test/Unit/Command/CronDisableTest.php
  src/Test/Unit/Command/CronEnableTest.php
  src/Test/Unit/Cron/SwitcherTest.php
  src/Test/Unit/Step/Deploy/DisableCronTest.php
  src/Test/Unit/Step/PostDeploy/EnableCronTest.php
Labels: Release: 2002.1.0, approved

#652 MAGECLOUD-4269: Refactor ValidateConfiguration to pass string levels
  scenario/build/generate.xml
  scenario/deploy.xml
  scenario/post-deploy.xml
  src/Step/ValidateConfiguration.php
  src/Test/Unit/Step/ValidateConfigurationTest.php
Labels: Release: 2002.1.0, approved

#651 MAGECLOUD-4127: Build fails with empty config.php
  composer.json
  src/Command/ConfigDump/Generate.php
  src/Config/Environment.php
  src/Config/Magento/Shared/Reader.php
  src/Config/Magento/Shared/Resolver.php
  src/Config/Module.php
  src/Config/Validator/Build/ConfigFileStructure.php
  src/Filesystem/Resolver/ConfigResolverInterface.php
  src/Filesystem/Resolver/SharedConfig.php
  src/StaticContent/Build/Option.php
  src/Test/Unit/Command/ConfigDump/GenerateTest.php
  src/Test/Unit/Config/EnvironmentDataTest.php
  src/Test/Unit/Config/EnvironmentTest.php
  src/Test/Unit/Config/Magento/Shared/ReaderTest.php
  src/Test/Unit/Config/Magento/Shared/ResolverTest.php
  src/Test/Unit/Config/Magento/Shared/_file/app/etc/config.php
  src/Test/Unit/Config/ModuleTest.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Config/Validator/Build/ConfigFileStructureTest.php
  src/Test/Unit/Filesystem/Resolver/SharedConfigTest.php
  src/Test/Unit/StaticContent/Build/OptionTest.php
  src/Test/Unit/StaticContent/Build/_files/app/etc/config.php
  tests/README.md
Labels: Release: 2002.1.0, approved

#654 MAGECLOUD-4849: Not full error log on failed execution of shell command
  src/Shell/Process.php
  src/Step/PostDeploy/TimeToFirstByte.php
  src/Step/PostDeploy/WarmUp.php
  src/Test/Functional/Acceptance/ErrorMessageCest.php
Labels: Release: 2002.1.0, approved

#655 Update DevDocs link in readme file
  README.md
Labels: Release: 2002.1.0, approved
