Repository magento/ece-tools, pull requests merged in 2019-05, with the labels that each got.

#476 MAGECLOUD-3345: Add Node.JS Docker Image
  src/Command/Docker/Build.php
  src/Docker/Compose/ProductionCompose.php
  src/Docker/ComposeManagerInterface.php
  src/Docker/Service/Config.php
  src/Docker/Service/ServiceFactory.php
  src/Test/Unit/Command/Docker/BuildTest.php
Labels: approved

#474 MAGECLOUD-3560: Disable integration tests for forks
  .travis.yml
  tests/travis/functional.sh
  tests/travis/integration.sh
  tests/travis/script.sh
  tests/travis/static-unit.sh
Labels: Release: 2002.0.19, approved

#483 MAGECLOUD-3577: Release ECE-Tools 2002.0.18
  composer.json
Labels: approved

#485 MAGECLOUD-3580: Env.php configs are not updated after deleting the ES service
  src/Config/Deploy/Writer.php
  src/Config/Shared.php
  src/Config/Shared/Writer.php
  src/Config/State.php
  src/Filesystem/Writer/WriterInterface.php
  src/Process/Deploy/DisableCron.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/DocumentRoot.php
  src/Process/Deploy/InstallUpdate/Update/SetAdminUrl.php
  src/Process/Deploy/SetCryptKey.php
  src/Test/Unit/Config/Deploy/WriterTest.php
  src/Test/Unit/Config/Shared/WriterTest.php
  src/Test/Unit/Config/SharedTest.php
  src/Test/Unit/Config/StateTest.php
  src/Test/Unit/Process/Deploy/DisableCronTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/DocumentRootTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Update/SetAdminUrlTest.php
  src/Test/Unit/Process/Deploy/SetCryptKeyTest.php
Labels: Release: 2002.0.18, approved

#484 MAGECLOUD-3178: Fix an Issue with Unrelated Warning Messages Appearing alongside Critical Error
  src/Process/ValidateConfiguration.php
  src/Test/Unit/Process/ValidateConfigurationTest.php
Labels: Release: 2002.0.19, qa

#487 MAGECLOUD-2824: Setting UPDATE_URLS to TRUE is not Possible for Some Environments
  dist/.magento.env.yaml
  src/Config/Schema.php
  src/Config/Stage/DeployInterface.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/Urls.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/UrlsTest.php
Labels: Release: 2002.0.19, approved

#489 Merge 2002.0 into develop
  composer.json
  src/Config/Deploy/Writer.php
  src/Config/Shared.php
  src/Config/Shared/Writer.php
  src/Config/State.php
  src/Filesystem/Writer/WriterInterface.php
  src/Process/Deploy/DisableCron.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/DocumentRoot.php
  src/Process/Deploy/InstallUpdate/Update/SetAdminUrl.php
  src/Process/Deploy/SetCryptKey.php
  src/Test/Unit/Config/Deploy/WriterTest.php
  src/Test/Unit/Config/Shared/WriterTest.php
  src/Test/Unit/Config/SharedTest.php
  src/Test/Unit/Config/StateTest.php
  src/Test/Unit/Process/Deploy/DisableCronTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/DocumentRootTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Update/SetAdminUrlTest.php
  src/Test/Unit/Process/Deploy/SetCryptKeyTest.php
Labels: approved

#491 MAGECLOUD-3603: Fix integration tests
  tests/integration/AbstractTest.php
  tests/travis/integration.sh
Labels: approved

#478 MAGECLOUD-2901: [Spike] Prefixes for DB Tables are not Considered
  src/Command/ConfigDump/Generate.php
  src/Cron/JobUnlocker.php
  src/DB/Connection.php
  src/DB/ConnectionInterface.php
  src/Process/Deploy/DisableGoogleAnalytics.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/Urls/Database.php
  src/Process/Deploy/InstallUpdate/Install/Setup.php
  src/Process/Deploy/InstallUpdate/Install/Setup/InstallCommandFactory.php
  src/StaticContent/Deploy/Option.php
  src/Test/Unit/Command/ConfigDump/GenerateTest.php
  src/Test/Unit/Cron/JobUnlockerTest.php
  src/Test/Unit/DB/ConnectionTest.php
  src/Test/Unit/Process/Deploy/DisableGoogleAnalyticsTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/Urls/DatabaseTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Install/Setup/InstallCommandFactoryTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Install/SetupTest.php
  src/Test/Unit/StaticContent/Deploy/OptionTest.php
  src/Test/Unit/Util/UrlManagerTest.php
  src/Util/UrlManager.php
Labels: Release: 2002.0.19, approved

#455 Add pub/static/.htaccess file to the exclude list
  src/Util/StaticContentCleaner.php
Labels: Partner: PHOENIX MEDIA GmbH, Release: 2002.0.19, approved, community

#490 MAGECLOUD-3475: Refactor Shell implementation
  composer.json
  src/Config/Magento/System.php
  src/Process/DbDump/DbDump.php
  src/Process/Deploy/CronProcessKill.php
  src/Shell/MagentoShell.php
  src/Shell/Process.php
  src/Shell/ProcessException.php
  src/Shell/ProcessFactory.php
  src/Shell/ProcessInterface.php
  src/Shell/Shell.php
  src/Shell/ShellInterface.php
  src/Shell/UtilityManager.php
  src/Test/Integration/ShellLoggingTest.php
  src/Test/Unit/Config/Magento/SystemTest.php
  src/Test/Unit/Patch/ApplierTest.php
  src/Test/Unit/Process/Build/ComposerDumpAutoloadTest.php
  src/Test/Unit/Process/DbDump/DbDumpTest.php
  src/Test/Unit/Process/Deploy/CronProcessKillTest.php
  src/Test/Unit/Process/SetProductionModeTest.php
  src/Test/Unit/Shell/MagentoShellTest.php
  src/Test/Unit/Shell/ProcessFactoryTest.php
  src/Test/Unit/Shell/ShellTest.php
  src/Test/Unit/Shell/UtilityManagerTest.php
  src/Test/Unit/Util/CpuTest.php
  src/Util/Cpu.php
  tests/integration/Bootstrap.php
  tests/integration/Shell/Shell.php
Labels: Release: 2002.0.19

#506 MAGECLOUD-3569: Improve UX by adding scripts
  .docker/.gitignore
  .docker/global.env
  .travis.yml
  composer.json
  dist/Makefile
  dist/docker-sync.yml
  dist/docker/README.md
  dist/docker/bin/docker
  src/Command/Docker/BuildIntegration.php
  src/Command/Docker/ConfigConvert.php
  src/Docker/Compose/DeveloperCompose.php
  src/Docker/Compose/FunctionalCompose.php
  src/Docker/Compose/IntegrationCompose.php
  src/Docker/Compose/ProductionCompose.php
  src/Docker/ComposeManagerFactory.php
  src/Docker/Config/DistGenerator.php
  src/Filesystem/DirectoryList.php
  src/Test/Unit/Command/Docker/ConfigConvertTest.php
  src/Test/Unit/Docker/Config/ConverterTest.php
  src/Test/Unit/Docker/Config/DistGeneratorTest.php
  src/Test/Unit/Filesystem/DirectoryListTest.php
  tests/travis/functional.sh
  tests/travis/integration.sh
Labels: Release: 2002.0.19, qa

#513 MAGECLOUD-3629: Rewrite AcceptanceTest remaining cases to use Cloud Docker
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Integration/AcceptanceTest.php
  tests/functional/Codeception/Docker.php
Labels: Release: 2002.0.19, review

#514 MAGECLOUD-3649: Rewrite Patch/ApplierTest to use Cloud Docker
  src/Test/Functional/Acceptance/PatchApplierCest.php
  src/Test/Integration/Patch/ApplierTest.php
  tests/functional/_data/files/patches/patch.patch
  tests/functional/_data/files/patches/target_file.md
  tests/functional/_data/files/patches/target_file_applied_patch.md
Labels: Release: 2002.0.19, approved

#482 MAGECLOUD-3510: Fix an Issue with db-dump Command Related to DEFINERS
  src/App/Container.php
  src/Command/DbDump.php
  src/DB/DumpGenerator.php
  src/Test/Unit/Command/DbDumpTest.php
  src/Test/Unit/DB/DumpGeneratorTest.php
Labels: Release: 2002.0.19, approved

#522 MAGECLOUD-3666: Rewrite Wizard Tests to use Cloud Docker
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Functional/Acceptance/AdminCredentialCest.php
  src/Test/Functional/Acceptance/CronCest.php
  src/Test/Functional/Acceptance/PatchApplierCest.php
  src/Test/Functional/Acceptance/PostDeployCest.php
  src/Test/Functional/Acceptance/ScdMatrixCest.php
  src/Test/Functional/Acceptance/UpgradeCest.php
  src/Test/Functional/Acceptance/WizardScdCest.php
  src/Test/Integration/Wizard/ScdOnBuildTest.php
  src/Test/Integration/Wizard/ScdOnDemandTest.php
  src/Test/Integration/Wizard/_files/config_scd_in_build.php
  src/Test/Integration/Wizard/_files/scd_on_demand_enabled.yaml
  src/Test/Integration/_files/.magento.env.yaml.scdondemand
  src/Test/Integration/_files/.magento.env.yaml.wrong_db_configuration
  src/Test/Integration/_files/modules/Magento/CronTest/Model/TestJob.php
  src/Test/Integration/_files/modules/Magento/CronTest/composer.json
  src/Test/Integration/_files/modules/Magento/CronTest/etc/crontab.xml
  src/Test/Integration/_files/modules/Magento/CronTest/etc/module.xml
  src/Test/Integration/_files/modules/Magento/CronTest/registration.php
  tests/functional/_data/files/scdinbuild/config.php
  tests/travis/prepare_functional_parallel.sh
Labels: Release: 2002.0.20, review

#523 MAGECLOUD-3668: Custom data in env.php removed after redeploy
  src/Config/Deploy/Writer.php
  src/Config/Shared.php
  src/Config/Shared/Writer.php
  src/Config/State.php
  src/Filesystem/Writer/WriterInterface.php
  src/Process/Deploy/DisableCron.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/DocumentRoot.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/SearchEngine.php
  src/Process/Deploy/InstallUpdate/Update/SetAdminUrl.php
  src/Process/Deploy/SetCryptKey.php
  src/Test/Unit/Config/Deploy/WriterTest.php
  src/Test/Unit/Config/Shared/WriterTest.php
  src/Test/Unit/Config/SharedTest.php
  src/Test/Unit/Config/StateTest.php
  src/Test/Unit/Process/Deploy/DisableCronTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/DocumentRootTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/SearchEngineTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Update/SetAdminUrlTest.php
  src/Test/Unit/Process/Deploy/SetCryptKeyTest.php
Labels: 2002.0, Release: 2002.0.19, approved

#524 MAGECLOUD-3677: Release ECE-Tools 2002.0.19
  composer.json
Labels: 2002.0, approved

#526 MAGECLOUD-3685: Back-port 2002.0 changes
  composer.json
  src/Config/Deploy/Writer.php
  src/Config/Shared.php
  src/Config/Shared/Writer.php
  src/Config/State.php
  src/Filesystem/Writer/WriterInterface.php
  src/Process/Deploy/DisableCron.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/DocumentRoot.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/SearchEngine.php
  src/Process/Deploy/InstallUpdate/Update/SetAdminUrl.php
  src/Process/Deploy/SetCryptKey.php
  src/Test/Unit/Config/Deploy/WriterTest.php
  src/Test/Unit/Config/Shared/WriterTest.php
  src/Test/Unit/Config/SharedTest.php
  src/Test/Unit/Config/StateTest.php
  src/Test/Unit/Process/Deploy/DisableCronTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/DocumentRootTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/SearchEngineTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Update/SetAdminUrlTest.php
  src/Test/Unit/Process/Deploy/SetCryptKeyTest.php
Labels: approved

#517 MAGECLOUD-3665: Unable to install 2.2.6 with ece-tools develop after shell refactoring
  src/Shell/Shell.php
  src/Test/Unit/Shell/ShellTest.php
Labels: Release: 2002.0.20, approved

#529 MAGECLOUD-3704: Magento cloud 2.1.x and 2.2.x installations are failing
  composer.json
  tests/functional/Codeception/Docker.php
  tests/functional/Robo/Tasks/DockerCompose/Run.php
Labels: Release: 2002.0.20, approved
