Repository magento/ece-tools, pull requests merged in 2019-07, with the labels that each got.

#547 MAGECLOUD-3535: Move Service Version Validation Higher and Merge ES/PHP Validation
  src/App/Container.php
  src/Command/Docker/Build.php
  src/Config/Factory/Cache.php
  src/Config/SearchEngine.php
  src/Config/SearchEngine/ElasticSuite.php
  src/Config/Validator/Deploy/ElasticSearchUsage.php
  src/Config/Validator/Deploy/ElasticSearchVersion.php
  src/Config/Validator/Deploy/ElasticSuiteIntegrity.php
  src/Config/Validator/Deploy/ServiceVersion.php
  src/Config/ValidatorInterface.php
  src/DB/Data/RelationshipConnectionFactory.php
  src/Docker/Compose/FunctionalCompose.php
  src/Docker/Compose/ProductionCompose.php
  src/Docker/Config/Relationship.php
  src/Docker/Service/Config.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/Amqp/Config.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/Session/Config.php
  src/Service/ConfigurationMismatchException.php
  src/Service/Database.php
  src/Service/ElasticSearch.php
  src/Service/RabbitMq.php
  src/Service/Redis.php
  src/Service/Service.php
  src/Service/ServiceFactory.php
  src/Service/ServiceInterface.php
  src/Service/Validator.php
  src/Test/Unit/Config/Factory/CacheTest.php
  src/Test/Unit/Config/Magento/SystemTest.php
  src/Test/Unit/Config/SearchEngine/ElasticSuiteTest.php
  src/Test/Unit/Config/SearchEngineTest.php
  src/Test/Unit/Config/System/VariablesTest.php
  src/Test/Unit/Config/Validator/Deploy/ElasticSearchUsageTest.php
  src/Test/Unit/Config/Validator/Deploy/ElasticSearchVersionTest.php
  src/Test/Unit/Config/Validator/Deploy/ElasticSuiteIntegrityTest.php
  src/Test/Unit/Config/Validator/Deploy/ServiceVersionTest.php
  src/Test/Unit/DB/Data/RelationshipConnectionFactoryTest.php
  src/Test/Unit/Docker/Service/ConfigTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/Amqp/ConfigTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/ConfigUpdate/Session/ConfigTest.php
  src/Test/Unit/Service/DatabaseTest.php
  src/Test/Unit/Service/ElasticSearchTest.php
  src/Test/Unit/Service/RabbitMqTest.php
  src/Test/Unit/Service/RedisTest.php
  src/Test/Unit/Service/ServiceFactoryTest.php
  src/Test/Unit/Service/ValidatorTest.php
Labels: Release: 2002.0.21, approved

#556 MAGECLOUD-2794: Update shell usages to use MagentoShell
  src/App/Container.php
  src/Config/Module.php
  src/Process/Build/CompileDi.php
  src/Process/Deploy/InstallUpdate/Install/ConfigImport.php
  src/Process/PostDeploy/CleanCache.php
  src/Process/PostDeploy/WarmUp/UrlsPattern.php
  src/Shell/MagentoShell.php
  src/Test/Unit/Config/ModuleTest.php
  src/Test/Unit/Process/Build/CompileDiTest.php
  src/Test/Unit/Process/Deploy/InstallUpdate/Install/ConfigImportTest.php
  src/Test/Unit/Process/PostDeploy/CleanCacheTest.php
  src/Test/Unit/Process/PostDeploy/WarmUp/UrlsPatternTest.php
  src/Test/Unit/Shell/MagentoShellTest.php
  src/Test/Unit/Util/MaintenanceModeSwitcherTest.php
  src/Test/Unit/Util/UrlManagerTest.php
  src/Util/MaintenanceModeSwitcher.php
  src/Util/UrlManager.php
Labels: Release: 2002.0.21, approved

#562 MAGECLOUD-3653: Change description for killing cron processes
  src/Process/Deploy/CronProcessKill.php
  src/Shell/Process.php
  src/Test/Unit/Process/Deploy/CronProcessKillTest.php
Labels: Release: 2002.0.21, approved

#561 MAGECLOUD-3816: Eliminate Docker config.env file
  src/Application.php
  src/Command/Docker/Build.php
  src/Command/Docker/ConfigConvert.php
  src/Command/Docker/GenerateDist.php
  src/Docker/Compose/FunctionalCompose.php
  src/Docker/Compose/ProductionCompose.php
  src/Docker/Config/Dist/Generator.php
  src/Docker/Config/Environment/Converter.php
  src/Docker/Config/Environment/Reader.php
  src/Docker/Service/ServiceFactory.php
  src/Service/ServiceFactory.php
  src/Service/ServiceMismatchException.php
  src/Service/Validator.php
  src/Shell/ProcessFactory.php
  src/Test/Unit/ApplicationTest.php
  src/Test/Unit/Command/Docker/Build/WriterTest.php
  src/Test/Unit/Command/Docker/BuildTest.php
  src/Test/Unit/Command/Docker/ConfigConvertTest.php
  src/Test/Unit/Command/Docker/GenerateDistTest.php
  src/Test/Unit/Config/Validator/Deploy/ServiceVersionTest.php
  src/Test/Unit/Docker/Config/Dist/GeneratorTest.php
  src/Test/Unit/Docker/Config/Environment/ConverterTest.php
  src/Test/Unit/Docker/Config/Environment/ReaderTest.php
  src/Test/Unit/Docker/Config/ReaderTest.php
  src/Test/Unit/Service/ServiceFactoryTest.php
Labels: approved

#563 MAGECLOUD-3714: Inject ECE Tools to Functional Tests
  .travis.yml
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Functional/Acceptance/AdminCredentialCest.php
  src/Test/Functional/Acceptance/CronCest.php
  src/Test/Functional/Acceptance/ElasticSearchCest.php
  src/Test/Functional/Acceptance/PatchApplierCest.php
  src/Test/Functional/Acceptance/PostDeployCest.php
  src/Test/Functional/Acceptance/ScdMatrixCest.php
  src/Test/Functional/Acceptance/UpgradeCest.php
  src/Test/Functional/Acceptance/WizardScdCest.php
  tests/functional/Codeception/Docker.php
  tests/functional/Robo/Tasks/DockerCompose/Run.php
Labels: Release: 2002.0.21, approved

#564 MAGECLOUD-3806: Error during app:config:import wasn't logged during setup:upgrade
  patches.json
  patches/MAGECLOUD-3806__failure_setup:upgrade_if_app:config:import_failed__2.2.0.patch
  patches/MAGECLOUD-3806__failure_setup:upgrade_if_app:config:import_failed__2.2.1.patch
  patches/MAGECLOUD-3806__failure_setup:upgrade_if_app:config:import_failed__2.3.0.patch
Labels: approved, qa

#568 MAGECLOUD-3929: Rename patches to avoid colon in naming
  patches.json
  patches/MAGECLOUD-3806__error_code_fix_for_setup_upgrade__2.2.0.patch
  patches/MAGECLOUD-3806__error_code_fix_for_setup_upgrade__2.2.1.patch
  patches/MAGECLOUD-3806__error_code_fix_for_setup_upgrade__2.3.0.patch
Labels: Release: 2002.0.21

#567 MAGECLOUD-3578 Add PHPStan to Static Tests set
  composer.json
  src/Command/ConfigDump.php
  src/Command/ConfigShow/Renderer.php
  src/Command/Dev/UpdateComposer.php
  src/Command/Dev/UpdateComposer/ComposerGenerator.php
  src/Command/PostDeploy.php
  src/Command/Wizard/IdealState.php
  src/Command/Wizard/ScdOnBuild.php
  src/Config/Database/MergedConfig.php
  src/Config/Database/SlaveConfig.php
  src/Config/Environment.php
  src/Config/Schema.php
  src/Config/Shared.php
  src/Config/Stage/Deploy.php
  src/Config/Stage/Deploy/MergedConfig.php
  src/Config/Validator/Build/BuildOptionsIni.php
  src/Config/Validator/IdealState.php
  src/DB/Connection.php
  src/DB/Data/RelationshipConnectionFactory.php
  src/Docker/Compose/DeveloperCompose.php
  src/Docker/Config/Environment/Reader.php
  src/Filesystem/Driver/File.php
  src/Http/ClientFactory.php
  src/Process/Build/BackupData/WritableDirectories.php
  src/Process/Deploy/InstallUpdate/ConfigUpdate/Urls/Database.php
  src/Process/Deploy/PreDeploy/ConfigUpdate/Cache.php
  src/Process/ValidateConfiguration.php
  src/Test/Unit/App/LoggerTest.php
  src/Test/Unit/Config/Validator/SchemaValidatorTest.php
  src/Test/Unit/Docker/Config/ReaderTest.php
  src/Test/Unit/Http/ClientFactoryTest.php
  src/Test/Unit/Http/PoolFactoryTest.php
  src/Test/Unit/Process/Build/BackupData/WritableDirectoriesTest.php
  src/Util/UrlManager.php
  tests/static/phpstan.neon
  tests/static/phpstan7.0.neon
  tests/travis/static-unit.sh
Labels: Release: 2002.0.21, approved

#548 MAGECLOUD-2514: Add List of Modules which were Enabled by module:refresh Command to cloud.log
  src/App/Container.php
  src/Command/ModuleRefresh.php
  src/Config/Module.php
  src/Process/Build/RefreshModules.php
  src/Test/Unit/Command/ModuleRefreshTest.php
  src/Test/Unit/Config/ModuleTest.php
  src/Test/Unit/Process/Build/RefreshModulesTest.php
Labels: Release: 2002.0.21, qa

#574 MAGECLOUD-3997: Fix autoload error in ece-tools
  composer.json
  src/Composer/ClearAutoload.php
  tests/static/phpstan.neon
  tests/static/phpstan7.0.neon
Labels: Release: 2002.0.21, approved

#560 MAGECLOUD-3866: Warm up functionality does not work if no store with 'default' code
  src/Process/PostDeploy/WarmUp/UrlsPattern.php
  src/Test/Unit/Process/PostDeploy/WarmUp/UrlsPatternTest.php
  src/Test/Unit/Util/UrlManagerTest.php
  src/Util/UrlManager.php
Labels: Release: 2002.0.21, approved
