Repository magento/ece-tools, pull requests merged in 2020-09, with the labels that each got.

#780 MCLOUD-6910: MC-37292: Make 'quality-patches' a hard dependency for ece-tools and soft dependency for magento-cloud-patches
  .github/workflows/ci.yaml
  .travis.yml
  composer.json
Labels: Progress: ready for delivery, Release: 2002.1.3

#781 MC-37699: Add support to read-only pub/static directory
  src/Config/Environment.php
  src/Config/EnvironmentData.php
  src/Step/Build/BackupData/StaticContent.php
  src/Step/Deploy/PreDeploy/CleanStaticContent.php
  src/Test/Unit/Config/EnvironmentDataTest.php
  src/Test/Unit/Config/EnvironmentTest.php
  src/Test/Unit/Step/Build/BackupData/StaticContentTest.php
  src/Test/Unit/Step/Deploy/PreDeploy/CleanStaticContentTest.php
  src/Util/BuildDirCopier.php
Labels: Progress: approved, Release: 2002.1.3

#782 MCLOUD-6937: Deployment is not failed if install Magento 2.4.0 with mysql search engine
  config/schema.error.yaml
  dist/error-codes.md
  src/App/Error.php
  src/Command/Dev/GenerateSchemaError.php
  src/Config/Validator/Deploy/ElasticSearchIntegrity.php
  src/Config/Validator/Deploy/SearchConfiguration.php
  src/Test/Unit/Config/Validator/Deploy/ElasticsearchIntegrityTest.php
  src/Test/Unit/Config/Validator/Deploy/SearchConfigurationTest.php
Labels: Progress: testing in progress, Release: 2002.1.3
