Repository magento/ece-tools, pull requests merged in 2020-03, with the labels that each got.

#687 MAGECLOUD-4890: Implement support for backup databases from split connections for `ece-tools`
  config/schema.yaml
  src/Command/DbDump.php
  src/DB/Data/ConnectionFactory.php
  src/DB/Dump.php
  src/DB/DumpGenerator.php
  src/DB/DumpInterface.php
  src/DB/DumpProcessor.php
  src/Test/Unit/Command/DbDumpTest.php
  src/Test/Unit/DB/Data/ConnectionFactoryTest.php
  src/Test/Unit/DB/DumpGeneratorTest.php
  src/Test/Unit/DB/DumpProcessorTest.php
  src/Test/Unit/DB/DumpTest.php
Labels: Progress: approved, Release: 2002.1.1

#699 MAGECLOUD-5529: ece-tools can't deploy magento if DB prefixes were enabled
  src/Config/State.php
  src/Test/Functional/Acceptance/DatabaseConfigurationCest.php
  src/Test/Unit/Config/StateTest.php
Labels: Progress: approved, Release: 2002.1.1

#692 MAGECLOUD-5306: Run the update command after enabling SPLIT_DB
  src/Step/Deploy/InstallUpdate/Update/Setup.php
  src/Step/Deploy/SplitDbConnection.php
  src/Step/Deploy/SplitDbConnection/SlaveConnection.php
  src/Test/Unit/Step/Deploy/InstallUpdate/Update/SetupTest.php
  src/Test/Unit/Step/Deploy/SplitDbConnection/SlaveConnectionTest.php
  src/Test/Unit/Step/Deploy/SplitDbConnectionTest.php
  src/Test/Unit/Util/UpgradeProcessTest.php
  src/Util/UpgradeProcess.php
Labels: Progress: approved, Release: 2002.1.1

#700 MAGECLOUD-4146: Cache warm-up script
  config/schema.yaml
  src/Config/Stage/PostDeployInterface.php
  src/Step/PostDeploy/WarmUp.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Step/PostDeploy/WarmUpTest.php
Labels: Progress: approved, improvement

#702 MAGECLOUD-5641: ECE-Tools directory copying is broken on Busybox
  config/services.xml
  src/Filesystem/DirectoryCopier/CopyStrategy.php
  src/Filesystem/DirectoryCopier/CopySubFolderStrategy.php
  src/Filesystem/DirectoryCopier/StrategyInterface.php
  src/Filesystem/Driver/File.php
  src/Shell/UtilityException.php
  src/Shell/UtilityManager.php
  src/Step/Deploy/InstallUpdate/Install/Setup.php
  src/Test/Unit/Filesystem/Driver/FileTest.php
  src/Test/Unit/Shell/UtilityManagerTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/Install/SetupTest.php
  src/Test/Unit/Util/StaticContentCompressorTest.php
  src/Test/Unit/Util/UpgradeProcessTest.php
  src/Util/StaticContentCompressor.php
  src/Util/UpgradeProcess.php
Labels: Progress: approved

#705 MCLOUD-5526: Improve the detection of master branch in ECE-Tools
  src/Config/Environment.php
  src/Test/Unit/Config/EnvironmentTest.php
Labels: Progress: approved, Release: 2002.1.1

#704 MCLOUD-4094: Update direct check of specific declaration in root composer.json
  src/Config/Validator/Build/ComposerFile.php
  src/Test/Unit/Config/Validator/Build/ComposerFileTest.php
  src/Test/Unit/Config/Validator/Build/_files/correct_composer_2.3_2.json
Labels: Progress: approved, Release: 2002.1.1
