Repository magento/ece-tools, pull requests merged in 2020-04, with the labels that each got.

#708 MCLOUD-5665: Improve git installation add support for packages with different structure
  src/Command/Dev/UpdateComposer/ComposerGenerator.php
  src/Test/Unit/Command/Dev/UpdateComposer/ComposerGeneratorTest.php
Labels: Progress: approved, Release: 2002.1.1

#712 MCLOUD-5442: Error is not displayed for extended scenario on deploy p…
  config/services.xml
  src/App/Container.php
  src/App/ContainerInterface.php
  src/App/ErrorHandler.php
  src/App/GenericException.php
  src/Scenario/Processor.php
  src/Shell/Process.php
  src/Shell/ProcessFactory.php
  src/Test/Unit/Scenario/ProcessorTest.php
Labels: Progress: approved, Release: 2002.1.1

#714 MCLOUD-5532: Add Versioning to Env Variable Schema
  config/schema.yaml
  src/Command/GenerateSchema.php
  src/Config/Schema.php
  src/Config/Schema/Validator.php
  src/Config/Stage/Deploy.php
  src/Config/Validator/Deploy/JsonFormatVariable.php
  src/Test/Unit/Command/GenerateSchemaTest.php
  src/Test/Unit/Config/Schema/ValidatorTest.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Config/Stage/DeployTest.php
  src/Test/Unit/Config/Validator/Deploy/JsonFormatVariableTest.php
Labels: Progress: approved, Release: 2002.1.1

#715 MCLOUD-4077: Align ideal state wizard with scenario-based deployment
  src/Config/Application/HookChecker.php
  src/Config/Validator/Deploy/PostDeploy.php
  src/Test/Unit/Config/Application/HookCheckerTest.php
Labels: 2002.1, Progress: approved, Release: 2002.1.1

#716 MCLOUD-5542: Add mapping for Elastic 7 version validator in ece-tools
  src/Config/Validator/Deploy/ElasticSearchVersion.php
  src/Test/Unit/Config/Validator/Deploy/ElasticSearchVersionTest.php
Labels: 2002.1, Progress: approved, Release: 2002.1.1

#719 MCLOUD-5732: Add ECE-Tools warning about MySQL search being used
  config/services.xml
  scenario/deploy.xml
  src/Config/SearchEngine.php
  src/Config/Validator/Deploy/DeprecatedSearchEngine.php
  src/Config/ValidatorException.php
  src/Config/ValidatorInterface.php
  src/Step/StepInterface.php
  src/Step/ValidateConfiguration.php
  src/Test/Unit/Config/Validator/Deploy/DeprecatedSearchEngineTest.php
Labels: 2002.1, Progress: approved, Release: 2002.1.1

#718 MCLOUD-5352: [ece-tools] Create a functional test for Split DB functionality
  src/Test/Functional/Acceptance/BackupDbCest.php
  src/Test/Functional/Acceptance/SplitDbCest.php
  src/Test/Functional/Acceptance/SplitDbWizardCest.php
Labels: Progress: approved, Progress: review, Release: 2002.1.1

#721 MCLOUD-5763: [Spike] Add GitHub workflow support
  .github/workflows/ci.yaml
  .travis.yml
  tests/travis/integration.sh
  tests/travis/static-unit.sh
Labels: Progress: approved
