Repository magento/ece-tools, pull requests merged in 2020-05, with the labels that each got.

#723 MCLOUD-5706: Add support of new ES option to ECE-Tools
  .github/workflows/ci.yaml
  config/services.xml
  scenario/deploy.xml
  src/App/GenericException.php
  src/Config/SearchEngine.php
  src/Config/SearchEngine/ElasticSuite.php
  src/Config/Validator/Deploy/ElasticSearchIntegrity.php
  src/Config/Validator/Deploy/ElasticSearchVersion.php
  src/Service/ElasticSearch.php
  src/Service/ServiceException.php
  src/Service/ServiceInterface.php
  src/Step/Deploy/InstallUpdate/Install/Setup/InstallCommandFactory.php
  src/Test/Unit/Config/SearchEngineTest.php
  src/Test/Unit/Config/Validator/Deploy/ElasticSearchVersionTest.php
  src/Test/Unit/Config/Validator/Deploy/ElasticsearchIntegrityTest.php
  src/Test/Unit/Service/ElasticSearchTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/Install/Setup/InstallCommandFactoryTest.php
  src/Test/Unit/Util/UrlManagerTest.php
  src/Util/UrlManager.php
Labels: Progress: qa in progress, Progress: review, Release: 2002.1.1

#722 Issue 667 : Extend environment data to be read from local file
  src/Config/EnvironmentData.php
  src/Test/Unit/Config/EnvironmentDataTest.php
Labels: Partner: Vaimo, Progress: approved, Release: 2002.0.1, partners-contribution

#727 MCLOUD-5897: Fix functional test of ece-tools
  src/Test/Functional/Acceptance/BackupDbCest.php
Labels: Progress: approved, Release: 2002.1.1

#725 MCLOUD-5883: UrlManager must respect routes with the attribute primary=true
  src/Test/Unit/Util/UrlManagerTest.php
  src/Util/UrlManager.php
Labels: Progress: qa in progress, Release: 2002.1.1

#728 MCLOUD-5939: Failed deploy with missed env.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/DbConnection.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/DbConnectionTest.php
Labels: Progress: approved, Release: 2002.1.1

#724 MCLOUD-5721: Implement support of new Redis features added in 2.3.5
  .travis.yml
  config/schema.yaml
  src/Config/Factory/Cache.php
  src/Config/Stage/DeployInterface.php
  src/Step/Deploy/PreDeploy/CleanRedisCache.php
  src/Step/Deploy/PreDeploy/ConfigUpdate/Cache.php
  src/Test/Functional/Acceptance/PatchApplierCest.php
  src/Test/Functional/Acceptance/RedisCest.php
  src/Test/Unit/Config/Factory/CacheTest.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Step/Deploy/PreDeploy/ConfigUpdate/CacheTest.php
  tests/travis/prepare_functional_parallel.sh
Labels: Progress: approved, Release: 2002.1.1, release-note-completed

#731 MCLOUD-5968: PostDeployCest is red
  config/scenario.xsd
  config/services.xml
  scenario/deploy.xml
  src/OnFail/Action/ActionException.php
  src/OnFail/Action/ActionInterface.php
  src/OnFail/Action/CreateDeployFailedFlag.php
  src/OnFail/Action/SkipAction.php
  src/Scenario/Collector/Action.php
  src/Scenario/Merger.php
  src/Scenario/Processor.php
  src/Scenario/Resolver.php
  src/Scenario/Sorter.php
  src/Step/SkipStep.php
  src/Test/Unit/OnFail/Action/CreateDeployFailedFlagTest.php
  src/Test/Unit/OnFail/Action/SkipActionTest.php
  src/Test/Unit/Scenario/MergerTest.php
  src/Test/Unit/Scenario/ProcessorTest.php
  src/Test/Unit/Scenario/ResolverTest.php
Labels: 2002.1, Progress: approved, Release: 2002.1.1

#734 Fixed a typo in the name of the constant
  src/Config/Factory/Cache.php
  src/Step/Deploy/PreDeploy/CleanRedisCache.php
  src/Step/Deploy/PreDeploy/ConfigUpdate/Cache.php
  src/Test/Unit/Config/Factory/CacheTest.php
  src/Test/Unit/Step/Deploy/PreDeploy/ConfigUpdate/CacheTest.php
Labels: Progress: review, Release: 2002.1.1

#732 MCLOUD-5991: Restore additional data in env.php if this file was removed
  scenario/deploy.xml
  src/App/Error.php
  src/Config/State.php
  src/Filesystem/Flag/Manager.php
  src/Filesystem/Flag/Pool.php
  src/Step/Deploy/InstallUpdate.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/CacheType.php
  src/Step/Deploy/PreDeploy/CheckState.php
  src/Step/Deploy/RemoveDeployFailedFlag.php
  src/Test/Unit/Config/StateTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/CacheTypeTest.php
  src/Test/Unit/Step/Deploy/InstallUpdateTest.php
  src/Test/Unit/Step/Deploy/PreDeploy/CheckStateTest.php
Labels: Progress: approved, Release: 2002.1.1
