Repository magento/ece-tools, pull requests merged in 2020-01, with the labels that each got.

#659 MAGECLOUD-4787: Update nesbot/carbon dependency
  composer.json
Labels: 2002.1, Release: 2002.1.0, approved

#650 MAGECLOUD-4674: Adding RabbitMQ 3.8 to supported versions
  config/eol.yaml
  src/Service/Validator.php
Labels: 2002.1, Release: 2002.1.0, approved

#663 MAGECLOUD-4982: De-composed magento-cloud-patches fail to apply locally
  dist/front-static.php.dist
  src/Filesystem/FileList.php
  src/Step/Build/CopyPubStatic.php
  src/Test/Unit/Step/Build/CopyPubStaticTest.php
Labels: 2002.1, approved

#664 MAGECLOUD-4979: Cleanup Composer Dependencies
  composer.json
  config/services.xml
  src/App/Container.php
Labels: Release: 2002.1.0, qa

#665 MAGECLOUD-4970: Move all environment variables to schema config
  config/schema.yaml
  config/services.xml
  dist/.magento.env.yaml
  src/Command/GenerateSchema.php
  src/Config/Schema.php
  src/Config/Schema/Formatter.php
  src/Config/Schema/Validator.php
  src/Config/Schema/Validator/Range.php
  src/Config/Schema/Validator/ValidatorFactory.php
  src/Test/Unit/Command/GenerateSchemaTest.php
  src/Test/Unit/Config/Schema/FormatterTest.php
  src/Test/Unit/Config/Schema/Validator/RangeTest.php
  src/Test/Unit/Config/Schema/ValidatorTest.php
  src/Test/Unit/Config/SchemaTest.php
  tests/functional/Codeception/Docker.php
Labels: Release: 2002.1.1, approved

#668 MAGECLOUD-5081: Stabilize Travis CI tests
  composer.json
  tests/functional/Codeception/Docker.php
Labels: 2002.1, Release: 2002.1.0, approved

#662 MAGECLOUD-2880: Rewrite text for notification about recommendation to enable maintenance before db-dump
  src/Command/DbDump.php
  src/Test/Unit/Command/DbDumpTest.php
Labels: Release: 2002.1.1, approved

#672 MAGECLOUD-5117: Fix failing cron Functional Test
  src/Test/Functional/Acceptance/Cron22Cest.php
  src/Test/Functional/Acceptance/CronCest.php
Labels: 2002.1, Release: 2002.1.0

#676 MAGECLOUD-5137: Merge 2002.1 branch into developer
  composer.json
  config/eol.yaml
  config/services.xml
  dist/front-static.php.dist
  src/App/Container.php
  src/Filesystem/FileList.php
  src/Service/Validator.php
  src/Step/Build/CopyPubStatic.php
  src/Test/Functional/Acceptance/Cron22Cest.php
  src/Test/Functional/Acceptance/CronCest.php
  src/Test/Unit/Step/Build/CopyPubStaticTest.php
Labels: Release: 2002.1.1, approved

#666 MAGECLOUD-4419: Add error details for failed functional tests in Travis
  codeception.dist.yml
  tests/functional/_support/FailedInfo.php
Labels: Release: 2002.1.1, approved

#677 MAGECLOUD-5146: Remove redundant validator in generate.xml scenarion
  scenario/build/generate.xml
Labels: 2002.1, Release: 2002.1.0, approved

#675 MAGECLOUD-5127: Update Constraints for Magento 2.4
  composer.json
Labels: Release: 2002.1.1, approved

#660 MAGECLOUD-3011: Add Baler Support
  config/schema.yaml
  config/services.xml
  dist/.magento.env.yaml
  scenario/build/generate.xml
  src/Config/Stage/BuildInterface.php
  src/Config/Validator/Build/BalerSupport.php
  src/Step/Build/RunBaler.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Config/Validator/Build/BalerSupportTest.php
  src/Test/Unit/Step/Build/RunBalerTest.php
Labels: Release: 2002.1.1, approved
