Repository magento/ece-tools, pull requests merged in 2020-02, with the labels that each got.

#682 Forward-port 2002.1 changes
  scenario/build/generate.xml
Labels: Progress: approved

#641 MAGECLOUD-3905: Implement split DB on Cloud using ece-tools
  config/schema.yaml
  scenario/deploy.xml
  src/App/Logger/Sanitizer.php
  src/Config/Database/DbConfig.php
  src/Config/Database/MergedConfig.php
  src/Config/Database/ResourceConfig.php
  src/Config/Database/SlaveConfig.php
  src/Config/Schema/Validator/SplitDb.php
  src/Config/Stage/DeployInterface.php
  src/Config/Validator/Deploy/DatabaseSplitConnection.php
  src/DB/Connection.php
  src/DB/Data/ConnectionFactory.php
  src/DB/Data/RelationshipConnectionFactory.php
  src/Filesystem/Flag/Manager.php
  src/Filesystem/Flag/Pool.php
  src/Service/Database.php
  src/Step/Deploy/DeployStaticContent/Generate.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/DbConnection.php
  src/Step/Deploy/InstallUpdate/Install/CleanupDbConfig.php
  src/Step/Deploy/InstallUpdate/Install/Setup/InstallCommandFactory.php
  src/Step/Deploy/RemoveDeployFailedFlag.php
  src/Step/Deploy/SplitDbConnection.php
  src/Test/Integration/Schema/ValidatorTest.php
  src/Test/Unit/App/Logger/SanitizerTest.php
  src/Test/Unit/Config/Database/DbConfigTest.php
  src/Test/Unit/Config/Database/MergedConfigTest.php
  src/Test/Unit/Config/Database/ResourceConfigTest.php
  src/Test/Unit/Config/Database/SlaveConfigTest.php
  src/Test/Unit/Config/Schema/Validator/SplitDbTest.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Config/Validator/Deploy/DatabaseSplitConnectionTest.php
  src/Test/Unit/DB/ConnectionTest.php
  src/Test/Unit/DB/Data/ConnectionFactoryTest.php
  src/Test/Unit/DB/Data/RelationshipConnectionFactoryTest.php
  src/Test/Unit/Service/DatabaseTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/DbConnectionTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/Install/CleanupDbConfigTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/Install/Setup/InstallCommandFactoryTest.php
  src/Test/Unit/Step/Deploy/RemoveDeployFailedFlagTest.php
  src/Test/Unit/Step/Deploy/SplitDbConnectionTest.php
Labels: Progress: approved, Progress: qa in progress, Release: 2002.1.1

#683 Adds Elasticsearch 7.5 to ECE tools for Magento 2.3.5
  config/eol.yaml
  src/Service/Validator.php
Labels: Partner: Zilker Technology, Progress: approved, Release: 2002.1.1, improvement, partners-contribution

#680 MAGECLOUD-4643: Add verbosity flag to bin/magento commands
  config/schema.yaml
  src/Command/ConfigDump.php
  src/Config/Module.php
  src/Step/Deploy/InstallUpdate/Install/ConfigImport.php
  src/Test/Unit/Command/ConfigDumpTest.php
  src/Test/Unit/Config/ModuleTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/Install/ConfigImportTest.php
Labels: Progress: approved, Release: 2002.1.1

#685 MAGECLOUD-4887: Implement wizard for split Db 'wizard:split-db-state'
  src/Application.php
  src/Command/Wizard/SplitDbState.php
  src/Test/Unit/ApplicationTest.php
  src/Test/Unit/Command/Wizard/SplitDbStateTest.php
Labels: Progress: approved, Release: 2002.1.1

#689 MAGECLOUD-5323: Update Cloud projects with proper licenses
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Progress: approved

#693 MAGECLOUD-5323: Update Cloud projects with proper licenses - fix bug_…
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Progress: approved

#691 MAGECLOUD-5394: Fix functional and static tests for 2002.0 branch
  .travis.yml
  composer.json
  src/Test/Functional/Acceptance/Cron21Cest.php
  src/Test/Functional/Acceptance/CronCest.php
  src/Test/Functional/Acceptance/Upgrade21Cest.php
  tests/functional/Codeception/Docker.php
  tests/static/phpstan.neon
Labels: 2002.0, Progress: approved, Release: 2002.0.23

#690 MAGECLOUD-5310: Issue with Magento 2002.0 and latest patches release 1.0.1
  dist/front-static.php.dist
  src/Filesystem/FileList.php
  src/Patch/Manager.php
  src/Test/Unit/Patch/ManagerTest.php
Labels: 2002.0, Progress: approved, Release: 2002.0.23, release-note-completed

#695 Release ECE-Tools 2002.0.23
  composer.json
Labels: Progress: approved, Release: 2002.0.23

#694 MAGECLOUD-5403: Fix unit tests for "Split DB" wizard setup
  src/Command/Wizard/SplitDbState.php
  src/Test/Unit/Command/Wizard/SplitDbStateTest.php
  src/Test/Unit/Config/SchemaTest.php
Labels: 2002.1, Progress: approved, Release: 2002.1.1

#670 MAGECLOUD-5147: Remove hard dependency on redis-cli
  .travis.yml
  composer.json
  src/Service/Adapter/CredisFactory.php
  src/Step/Deploy/PreDeploy/CleanRedisCache.php
  src/Test/Unit/Step/Deploy/PreDeploy/CleanRedisCacheTest.php
Labels: Progress: qa in progress, community, feature request, improvement
