Repository magento/ece-tools, pull requests merged in 2020-06, with the labels that each got.

#730 MCLOUD-5941: Applying patches is happening too late
  scenario/build/generate.xml
Labels: Progress: approved, Release: 2002.1.1

#735 MCLOUD-6120: Crypt key absence message appear on installation process
  src/Config/Environment.php
  src/Config/Validator/Deploy/AdminData.php
  src/Step/Deploy/SetCryptKey.php
  src/Test/Unit/Step/Deploy/SetCryptKeyTest.php
Labels: 2002.1, Progress: qa in progress, Release: 2002.1.1

#736 MCLOUD-6137: Remove error log at the beginning of deploy phase
  src/Step/Deploy/RemoveDeployFailedFlag.php
  src/Test/Unit/Step/Deploy/RemoveDeployFailedFlagTest.php
Labels: 2002.1, Progress: approved, Release: 2002.1.1

#740 Fix typo in default subject line
  src/App/Logger/HandlerFactory.php
Labels: Progress: approved, Release: 2002.1.1

#739 Add doc requirements to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Progress: review

#737 MCLOUD-6144: Adjust service validators prior to 2.4.0 version
  config/eol.yaml
  src/Config/Validator/Deploy/ElasticSearchVersion.php
  src/Service/Validator.php
  src/Test/Unit/Config/Validator/Deploy/ElasticSearchVersionTest.php
  src/Test/Unit/Service/ValidatorTest.php
Labels: 2002.1, Progress: approved, Release: 2002.1.1

#748 Bump version
  composer.json
Labels: Progress: approved

#747 MCLOUD-6071: Implement CLI command to retrieve all errors from the last deployment
  src/Application.php
  src/Command/ErrorShow.php
  src/Test/Unit/ApplicationTest.php
  src/Test/Unit/Command/ErrorShowTest.php
Labels: Progress: review, Release: 2002.1.2

#749 Clone only latest commit in case branch checkout
  src/Command/Dev/UpdateComposer/ComposerGenerator.php
  src/Test/Unit/Command/Dev/UpdateComposer/ComposerGeneratorTest.php
  src/Test/Unit/Command/Dev/UpdateComposer/_files/expected_composer.php
Labels: 2002.1, Progress: qa in progress, Progress: review, Release: 2002.1.2
