Repository magento/ece-tools, pull requests merged in 2020-07, with the labels that each got.

#755 MCLOUD-6381: Update error descriptions
  config/schema.error.yaml
  dist/error-codes.md
  src/Command/ErrorShow.php
  src/Config/Schema/Validator/SplitDb.php
  src/Config/Validator/Deploy/DebugLogging.php
  src/Config/Validator/Deploy/ElasticSearchUsage.php
  src/Config/Validator/Deploy/PhpVersion.php
  src/Config/Validator/Deploy/ReportDirNestingLevel.php
  src/Config/Validator/Deploy/SolrIntegrity.php
  src/DB/Data/ConnectionFactory.php
  src/DB/Data/RelationshipConnectionFactory.php
  src/Filesystem/DirectoryCopier/StrategyFactory.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/DbConnection.php
  src/Step/Deploy/SplitDbConnection.php
  src/Step/Deploy/SplitDbConnection/SlaveConnection.php
  src/Test/Functional/Acceptance/ReportDirNestingLevelCest.php
  src/Test/Functional/Acceptance/SplitDbCest.php
  src/Test/Integration/Schema/ValidatorTest.php
  src/Test/Unit/Command/ErrorShowTest.php
  src/Test/Unit/Config/Schema/Validator/SplitDbTest.php
  src/Test/Unit/Config/Validator/Deploy/ElasticSearchVersionTest.php
  src/Test/Unit/Config/Validator/Deploy/ReportDirNestingLevelTest.php
  src/Test/Unit/Config/Validator/Deploy/SolrIntegrityTest.php
  src/Test/Unit/DB/Data/ConnectionFactoryTest.php
  src/Test/Unit/DB/Data/RelationshipConnectionFactoryTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/StrategyFactoryTest.php
  src/Test/Unit/Scenario/Collector/ScenarioTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/DbConnectionTest.php
  src/Test/Unit/Step/Deploy/SplitDbConnection/SlaveConnectionTest.php
  src/Test/Unit/Step/Deploy/SplitDbConnectionTest.php
Labels: Progress: approved, Release: 2002.1.2

#754 MCLOUD-6376: Fixed: single-module repo files are copied to project root
  src/Command/Dev/UpdateComposer/ComposerGenerator.php
  src/Test/Unit/Command/Dev/UpdateComposer/ComposerGeneratorTest.php
  src/Test/Unit/Command/Dev/UpdateComposer/_files/app/repo5/composer.json
  src/Test/Unit/Command/Dev/UpdateComposer/_files/expected_composer.php
Labels: Progress: qa in progress, Release: 2002.1.2

#756 Forward-port 2002.1
  composer.json
Labels: 2002.1

#750 MCLOUD-6375: MC-34668: Introduce environment variable to store a list of quality p…
  config/schema.yaml
  scenario/deploy.xml
  src/Config/Stage/BuildInterface.php
  src/Filesystem/FileList.php
  src/Patch/Manager.php
  src/Step/Build/ApplyPatches.php
  src/Step/Deploy/PreDeploy/RestorePatchLog.php
  src/Test/Unit/Config/SchemaTest.php
  src/Test/Unit/Patch/ManagerTest.php
  src/Test/Unit/Step/Build/ApplyPatchesTest.php
  src/Test/Unit/Step/Deploy/PreDeploy/RestorePatchLogTest.php
Labels: Progress: approved, Release: 2002.1.2

#745 MCLOUD-6135: Every step should throw only StepException
  src/Scenario/Processor.php
  src/StaticContent/ThreadCountOptimizer.php
  src/Step/Build/DeployStaticContent.php
  src/Step/Build/DeployStaticContent/Generate.php
  src/Step/Build/PreBuild.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/Amqp.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/CronConsumersRunner.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/DbConnection.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/DocumentRoot.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/Lock.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/Session.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/Urls.php
  src/Step/Deploy/PreDeploy/RestoreWritableDirectories.php
  src/Step/Deploy/SplitDbConnection.php
  src/Step/PostDeploy/Backup.php
  src/Step/SetProductionMode.php
  src/Step/SkipStep.php
  src/Test/Unit/Scenario/ProcessorTest.php
  src/Test/Unit/Step/Build/DeployStaticContent/GenerateTest.php
  src/Test/Unit/Step/Build/DeployStaticContentTest.php
  src/Test/Unit/Step/Build/PreBuildTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/AmqpTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/CronConsumersRunnerTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/DocumentRootTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/LockTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/SessionTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/UrlsTest.php
  src/Test/Unit/Step/Deploy/PreDeploy/RestoreWritableDirectoriesTest.php
Labels: Release: 2002.1.2

#757 MCLOUD-6235: Cover new functionality with functional tests
  src/Test/Functional/Acceptance/ErrorCodesCest.php
  tests/functional/_data/files/error_codes/.magento.env.fail.yaml
  tests/functional/_data/files/error_codes/.magento.env.success.yaml
Labels: Progress: review, Release: 2002.1.2

#759 MCLOUD-6485: Add validator for braintree variable existence
  config/schema.error.yaml
  dist/error-codes.md
  scenario/build/generate.xml
  scenario/deploy.xml
  src/App/Error.php
  src/App/ErrorInfo.php
  src/App/Logger/LineFormatterFactory.php
  src/Config/Validator/Build/MagentoAppYaml.php
  src/Config/Validator/Deploy/EnvironmentVariables.php
  src/Config/Validator/ResultFactory.php
  src/Test/Unit/App/Logger/LineFormatterFactoryTest.php
  src/Test/Unit/Config/Schema/Validator/RangeTest.php
  src/Test/Unit/Config/Schema/Validator/SplitDbTest.php
  src/Test/Unit/Config/Schema/ValidatorTest.php
  src/Test/Unit/Config/Validator/Build/MagentoAppYamlTest.php
  src/Test/Unit/Config/Validator/Deploy/EnvironmentVariablesTest.php
  src/Test/Unit/Config/Validator/ResultFactoryTest.php
Labels: Progress: approved, Release: 2002.1.2

#761 MCLOUD-6536: MC-36032: ECE-Patches apply command updates
  src/Patch/Manager.php
  src/Step/Build/ApplyPatches.php
  src/Test/Unit/Patch/ManagerTest.php
  src/Test/Unit/Step/Build/ApplyPatchesTest.php
Labels: Progress: on hold, Release: 2002.1.2

#763 MCLOUD-6530: Fix an issue with empty error code in the StepException
  config/schema.error.yaml
  dist/error-codes.md
  src/App/Error.php
  src/Command/Dev/GenerateSchemaError.php
  src/Config/Validator/Deploy/ElasticSearchIntegrity.php
  src/Step/ValidateConfiguration.php
  src/Test/Unit/Config/Validator/Deploy/ElasticsearchIntegrityTest.php
  src/Test/Unit/Step/ValidateConfigurationTest.php
Labels: Progress: approved, Release: 2002.1.2
