Repository magento/ece-tools, pull requests merged in 2020-08, with the labels that each got.

#760 MCLOUD-6221: Add specific error code in some steps
  config/schema.error.yaml
  dist/error-codes.md
  src/App/Error.php
  src/Filesystem/DirectoryCopier/CopyStrategy.php
  src/Filesystem/DirectoryCopier/CopySubFolderStrategy.php
  src/Filesystem/DirectoryCopier/SubSymlinkStrategy.php
  src/Filesystem/DirectoryCopier/SymlinkStrategy.php
  src/Filesystem/RecoverableDirectoryList.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/Amqp.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/CronConsumersRunner.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/DocumentRoot.php
  src/Step/Deploy/InstallUpdate/ConfigUpdate/Session.php
  src/Step/Deploy/SetCryptKey.php
  src/Step/Deploy/SplitDbConnection.php
  src/Step/PostDeploy/Backup.php
  src/Test/Unit/Filesystem/DirectoryCopier/CopyStrategyTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/CopySubFolderStrategyTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/SubSymlinkStrategyTest.php
  src/Test/Unit/Filesystem/DirectoryCopier/SymlinkStrategyTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/AmqpTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/CronConsumersRunnerTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/DocumentRootTest.php
  src/Test/Unit/Step/Deploy/InstallUpdate/ConfigUpdate/SessionTest.php
  src/Test/Unit/Step/Deploy/SetCryptKeyTest.php
  src/Test/Unit/Step/Deploy/SplitDbConnectionTest.php
  src/Test/Unit/Step/PostDeploy/BackupTest.php
  src/Test/Unit/Util/BuildDirCopierTest.php
  src/Util/BuildDirCopier.php
Labels: Progress: ready for delivery, Release: 2002.1.2

#751 MCLOUD-6327: REDIS_BACKEND should work with Magento since 2.3.0
  codeception.dist.yml
  src/Config/Factory/Cache.php
  src/Step/Deploy/PreDeploy/CleanRedisCache.php
  src/Step/Deploy/PreDeploy/ConfigUpdate/Cache.php
  src/Test/Functional/Acceptance/RedisCest.php
  src/Test/Functional/Acceptance/RedisPhp71Cest.php
  src/Test/Functional/Acceptance/RedisPhp72Cest.php
  src/Test/Functional/Acceptance/RedisPhp73Cest.php
  src/Test/Unit/Config/Factory/CacheTest.php
  src/Test/Unit/Step/Deploy/PreDeploy/ConfigUpdate/CacheTest.php
Labels: Progress: ready for delivery, Release: 2002.1.2

#766 MCLOUD-6623: Remove ES 7.4 from service validator
  codeception.dist.yml
  src/Service/Validator.php
  src/Test/Unit/Service/ValidatorTest.php
Labels: Progress: ready for delivery, Release: 2002.1.2

#767 Bump version and dependencies
  composer.json
Labels: Progress: review, Release: 2002.1.2

#769 MCLOUD-6698: Update deploy ES version config validator
  src/Config/Validator/Deploy/ElasticSearchVersion.php
  src/Test/Unit/Config/Validator/Deploy/ElasticSearchVersionTest.php
Labels: Partner: Ziffity, Progress: ready for delivery, Release: 2002.1.3, partners-contribution

#772 MCLOUD-6712: Fix error method parameters for DatabaseSplitConnection validator
  src/Config/Validator/Deploy/DatabaseSplitConnection.php
  src/Test/Unit/Config/Validator/Deploy/DatabaseSplitConnectionTest.php
Labels: Progress: approved, Release: 2002.1.3

#771 MCLOUD-6708: Add warning if MAGE_MODE was set as not production
  config/schema.error.yaml
  dist/error-codes.md
  scenario/deploy.xml
  src/App/Error.php
  src/Config/EnvironmentData.php
  src/Config/EnvironmentDataInterface.php
  src/Config/Validator/Deploy/MageModeVariable.php
  src/Test/Unit/Config/EnvironmentDataTest.php
  src/Test/Unit/Config/Validator/Deploy/MageModeVariableTest.php
Labels: Progress: testing in progress, Release: 2002.1.3, release-note-completed

#773 MCLOUD-5563: Add information about warm-up concurrency into log
  src/Step/PostDeploy/WarmUp.php
  src/Test/Unit/Step/PostDeploy/WarmUpTest.php
Labels: Progress: ready for delivery, Release: 2002.1.3
